

* Alpha Vision

** Learning Techniques
*** Ralph Vince - Mathematics for Market
    DEADLINE: <2016-09-28 qua>
    Provide a schedule and a resume on the subject.

*** Quantitative Trading and Money Management

** Trends
   Calculate trends: BB; HMA; ATR; Stochastic; MACD

*** DONE Enum for Trends
    DEADLINE: <2016-08-26 sex>

*** DONE Implement missing indicators on AV
    DEADLINE: <2016-08-26 sex>
    - ok ATR
    - ok Stochastic
    - ok MACD
    - RSI?

*** DONE Log rotate positions csv
    - create a Log class that can also send email or update spreadsheets
    - flush file handler (work)

*** TODO provide a trend input structure / for each trend type

** Positions/Trader
   Deal with positions and execute entry/exit points.

*** Trader Algorithms
    DEADLINE: <2016-09-03 sáb>
    Trend Types:
    - trending <- move neutral / bull / bear
      HMA / BB channel / MACD
    - move strength <- play validation
      Stochastic / BB above/bellow std2
    - pivot levels <- play positions lines
      Pivot / Fibonacci / MAs / BB top/middle/bottom lines
    - volatility <- play type scalp / breakout
      ATR / Chaikin
    - signals <- whether it shall put an order
      HMA periods cross / MACD main & signal cross / Stochastic main & signal cross

    Algorithm Types:
    - Trend inclined (use major/current/fast trends)
    - TradingRange Helper! (signals with support&resistance levels)
    - Scalper (low volatility under fast timeframes)
    - Swinger (higher volatility & using pivot levels on slower timeframes)
    - Orchestra: macd for signals, stochastic for confirmation (overbought/oversold)
      and BB for entry/exit points.

**** Scalper algorithm

ATR (14 / 80) <- sets volatility | whether it should scalp or trend
HMA trend (20, 50 / 50, 200) <- sets trend neutral/positive/negative
BB trend (BB2 / BB3 / BB4) <- sets entry exit points
Stoch signal|main (21, 45) <- sets whether it shall pull the trigger

*** Trader timeframes

**** TODO pass positions to different timeframes handlers

**** TODO Update existing positions

*** Risk & Reward Optimization

** Signals Comparison
   Calculate and use Trends to capture signals.
   - SpreadSheet results formula:
     =sum(FILTER(H2:H224, I2:I224 <> "cancelled", D2:D224 > "2000.01.01 00:00:00"))
     =sum(filter(N2:N1113, regexmatch(O2:O1113, "[5]")))

*** TODO Algorithmic exits on bad entries
     on Overbought/Oversold entries going against it, can workout
     some good exits

*** TODO Check/compare different algorithm trade signals
    Those implemented on Trader Algorithms

** MQL

*** use external DLLs
*** Flux Signals
